"""Core subpackage for pi.coding_agent — session management, bash execution, extensions, and tools."""

from pi.coding_agent.core.agent_session import (
    DEFAULT_THINKING_LEVEL,
    AgentSession,
    AgentSessionConfig,
    AgentSessionEvent,
    AgentSessionEventListener,
    AutoCompactionEndEvent,
    AutoCompactionStartEvent,
    AutoRetryEndEvent,
    AutoRetryStartEvent,
    PromptOptions,
    SessionStats,
)
from pi.coding_agent.core.auth_storage import (
    ApiKeyCredential,
    AuthCredential,
    AuthStorage,
    AuthStorageBackend,
    AuthStorageData,
    FileAuthStorageBackend,
    InMemoryAuthStorageBackend,
    OAuthCredential,
)
from pi.coding_agent.core.bash_executor import (
    BashExecutorOptions,
    BashResult,
    execute_bash,
    execute_bash_with_operations,
)
from pi.coding_agent.core.compaction import (
    DEFAULT_COMPACTION_SETTINGS,
    SUMMARIZATION_SYSTEM_PROMPT,
    BranchPreparation,
    BranchSummaryDetails,
    BranchSummaryResult,
    CollectEntriesResult,
    CompactionDetails,
    CompactionPreparation,
    CompactionResult,
    CompactionSettings,
    ContextUsageEstimate,
    CutPointResult,
    FileOperations,
    GenerateBranchSummaryOptions,
    calculate_context_tokens,
    collect_entries_for_branch_summary,
    compact,
    compute_file_lists,
    create_file_ops,
    estimate_context_tokens,
    estimate_tokens,
    extract_file_ops_from_message,
    find_cut_point,
    find_turn_start_index,
    format_file_operations,
    generate_branch_summary,
    generate_summary,
    get_last_assistant_usage,
    prepare_branch_entries,
    prepare_compaction,
    serialize_conversation,
    should_compact,
)
from pi.coding_agent.core.config import (
    CONFIG_DIR_NAME,
    get_agent_dir,
    get_prompts_dir,
)
from pi.coding_agent.core.event_bus import EventBus, create_event_bus
from pi.coding_agent.core.exec import ExecOptions, ExecResult, exec_command
from pi.coding_agent.core.export_html.ansi_to_html import (
    ansi_lines_to_html,
    ansi_to_html,
)
from pi.coding_agent.core.extensions import (
    Extension,
    ExtensionActions,
    ExtensionAPI,
    ExtensionCommandContext,
    ExtensionCommandContextActions,
    ExtensionContext,
    ExtensionContextActions,
    ExtensionError,
    ExtensionFactory,
    ExtensionFlag,
    ExtensionRunner,
    ExtensionRuntime,
    ExtensionShortcut,
    LoadExtensionsResult,
    RegisteredCommand,
    RegisteredTool,
    ToolDefinition,
    create_extension,
    create_extension_runtime,
    discover_and_load_extensions,
    emit_session_shutdown_event,
    load_extension_from_factory,
    load_extensions,
    wrap_registered_tool,
    wrap_registered_tools,
    wrap_tool_with_extensions,
    wrap_tools_with_extensions,
)
from pi.coding_agent.core.keybindings import (
    DEFAULT_APP_KEYBINDINGS,
    DEFAULT_KEYBINDINGS,
)
from pi.coding_agent.core.messages import (
    BRANCH_SUMMARY_PREFIX,
    BRANCH_SUMMARY_SUFFIX,
    COMPACTION_SUMMARY_PREFIX,
    COMPACTION_SUMMARY_SUFFIX,
    BashExecutionMessage,
    BranchSummaryMessage,
    CompactionSummaryMessage,
    CustomMessage,
    bash_execution_to_text,
    convert_to_llm,
    create_branch_summary_message,
    create_compaction_summary_message,
    create_custom_message,
)
from pi.coding_agent.core.model_registry import (
    ModelOverride,
    ModelRegistry,
    ProviderConfigInput,
    ProviderOverride,
    clear_api_key_cache,
)
from pi.coding_agent.core.model_resolver import (
    DEFAULT_MODEL_PER_PROVIDER,
    InitialModelResult,
    ParsedModelResult,
    ResolveCliModelResult,
    ScopedModel,
    find_initial_model,
    parse_model_pattern,
    resolve_cli_model,
    resolve_model_scope,
    restore_model_from_session,
)
from pi.coding_agent.core.package_manager import (
    DefaultPackageManager,
    MissingSourceAction,
    PackageManager,
    PathMetadata,
    ProgressCallback,
    ProgressEvent,
    ResolvedPaths,
    ResolvedResource,
    create_package_manager,
)
from pi.coding_agent.core.prompt_templates import (
    PromptTemplate,
    expand_prompt_template,
    load_prompt_templates,
    parse_command_args,
    substitute_args,
)
from pi.coding_agent.core.resolve_config_value import (
    clear_config_value_cache,
    resolve_config_value,
    resolve_headers,
)
from pi.coding_agent.core.resource_loader import (
    DefaultResourceLoader,
    DefaultResourceLoaderOptions,
    ResourceDiagnostic,
    ResourceLoader,
)
from pi.coding_agent.core.sdk import (
    CreateAgentSessionOptions,
    CreateAgentSessionResult,
    create_agent_session,
)
from pi.coding_agent.core.session_manager import (
    CURRENT_SESSION_VERSION,
    BranchSummaryEntry,
    CompactionEntry,
    CustomEntry,
    CustomMessageEntry,
    FileEntry,
    LabelEntry,
    ModelChangeEntry,
    NewSessionOptions,
    SessionContext,
    SessionEntry,
    SessionHeader,
    SessionInfo,
    SessionInfoEntry,
    SessionManager,
    SessionMessageEntry,
    SessionTreeNode,
    ThinkingLevelChangeEntry,
    build_session_context,
    find_most_recent_session,
    get_latest_compaction_entry,
    load_entries_from_file,
    migrate_session_entries,
    parse_session_entries,
)
from pi.coding_agent.core.settings_manager import (
    BranchSummarySettings,
    FileSettingsStorage,
    ImageSettings,
    InMemorySettingsStorage,
    MarkdownSettings,
    PackageSource,
    PackageSourceObject,
    RetrySettings,
    Settings,
    SettingsError,
    SettingsManager,
    SettingsScope,
    SettingsStorage,
    TerminalSettings,
    ThinkingBudgetsSettings,
)
from pi.coding_agent.core.settings_manager import (
    CompactionSettings as SettingsCompactionSettings,
)
from pi.coding_agent.core.skills import (
    LoadSkillsResult,
    ParsedSkillBlock,
    Skill,
    SkillFrontmatter,
    format_skills_for_prompt,
    load_skills,
    load_skills_from_dir,
    parse_skill_block,
)
from pi.coding_agent.core.system_prompt import (
    BuildSystemPromptOptions,
    build_system_prompt,
)
from pi.coding_agent.core.timings import (
    print_timings,
    time,
)
from pi.coding_agent.core.tools import (
    BashTool,
    EditTool,
    FindTool,
    GrepTool,
    LsTool,
    ReadTool,
    WriteTool,
)

__all__ = [
    # constants
    "BRANCH_SUMMARY_PREFIX",
    "BRANCH_SUMMARY_SUFFIX",
    "COMPACTION_SUMMARY_PREFIX",
    "COMPACTION_SUMMARY_SUFFIX",
    "CONFIG_DIR_NAME",
    "CURRENT_SESSION_VERSION",
    "DEFAULT_APP_KEYBINDINGS",
    "DEFAULT_COMPACTION_SETTINGS",
    "DEFAULT_KEYBINDINGS",
    "DEFAULT_MODEL_PER_PROVIDER",
    "DEFAULT_THINKING_LEVEL",
    "SUMMARIZATION_SYSTEM_PROMPT",
    # agent_session
    "AgentSession",
    "AgentSessionConfig",
    "AgentSessionEvent",
    "AgentSessionEventListener",
    # auth_storage
    "ApiKeyCredential",
    "AuthCredential",
    "AuthStorage",
    "AuthStorageBackend",
    "AuthStorageData",
    "AutoCompactionEndEvent",
    "AutoCompactionStartEvent",
    "AutoRetryEndEvent",
    "AutoRetryStartEvent",
    # messages
    "BashExecutionMessage",
    # bash_executor
    "BashExecutorOptions",
    "BashResult",
    # tools
    "BashTool",
    # compaction
    "BranchPreparation",
    "BranchSummaryDetails",
    "BranchSummaryEntry",
    "BranchSummaryMessage",
    "BranchSummaryResult",
    "BranchSummarySettings",
    # system_prompt
    "BuildSystemPromptOptions",
    "CollectEntriesResult",
    "CompactionDetails",
    "CompactionEntry",
    "CompactionPreparation",
    "CompactionResult",
    "CompactionSettings",
    "CompactionSummaryMessage",
    "ContextUsageEstimate",
    # sdk
    "CreateAgentSessionOptions",
    "CreateAgentSessionResult",
    "CustomEntry",
    "CustomMessage",
    "CustomMessageEntry",
    "CutPointResult",
    # package_manager
    "DefaultPackageManager",
    # resource_loader
    "DefaultResourceLoader",
    "DefaultResourceLoaderOptions",
    "EditTool",
    # event_bus
    "EventBus",
    # exec
    "ExecOptions",
    "ExecResult",
    # extensions
    "Extension",
    "ExtensionAPI",
    "ExtensionActions",
    "ExtensionCommandContext",
    "ExtensionCommandContextActions",
    "ExtensionContext",
    "ExtensionContextActions",
    "ExtensionError",
    "ExtensionFactory",
    "ExtensionFlag",
    "ExtensionRunner",
    "ExtensionRuntime",
    "ExtensionShortcut",
    # auth_storage
    "FileAuthStorageBackend",
    "FileEntry",
    "FileOperations",
    # settings_manager
    "FileSettingsStorage",
    "FindTool",
    "GenerateBranchSummaryOptions",
    "GrepTool",
    "ImageSettings",
    "InMemoryAuthStorageBackend",
    "InMemorySettingsStorage",
    # model_resolver
    "InitialModelResult",
    "LabelEntry",
    "LoadExtensionsResult",
    "LoadSkillsResult",
    "LsTool",
    "MarkdownSettings",
    "MissingSourceAction",
    "ModelChangeEntry",
    # model_registry
    "ModelOverride",
    "ModelRegistry",
    "NewSessionOptions",
    "OAuthCredential",
    "PackageManager",
    "PackageSource",
    "PackageSourceObject",
    "ParsedModelResult",
    # skills
    "ParsedSkillBlock",
    "PathMetadata",
    "ProgressCallback",
    "ProgressEvent",
    "PromptOptions",
    # prompt_templates
    "PromptTemplate",
    "ProviderConfigInput",
    "ProviderOverride",
    "ReadTool",
    "RegisteredCommand",
    "RegisteredTool",
    "ResolveCliModelResult",
    "ResolvedPaths",
    "ResolvedResource",
    "ResourceDiagnostic",
    "ResourceLoader",
    "RetrySettings",
    "ScopedModel",
    "SessionContext",
    "SessionEntry",
    "SessionHeader",
    "SessionInfo",
    "SessionInfoEntry",
    "SessionManager",
    "SessionMessageEntry",
    "SessionStats",
    "SessionTreeNode",
    "Settings",
    "SettingsCompactionSettings",
    "SettingsError",
    "SettingsManager",
    "SettingsScope",
    "SettingsStorage",
    "Skill",
    "SkillFrontmatter",
    "TerminalSettings",
    "ThinkingBudgetsSettings",
    "ThinkingLevelChangeEntry",
    "ToolDefinition",
    "WriteTool",
    # functions
    "ansi_lines_to_html",
    "ansi_to_html",
    "bash_execution_to_text",
    "build_session_context",
    "build_system_prompt",
    "calculate_context_tokens",
    "clear_api_key_cache",
    "clear_config_value_cache",
    "collect_entries_for_branch_summary",
    "compact",
    "compute_file_lists",
    "convert_to_llm",
    "create_agent_session",
    "create_branch_summary_message",
    "create_compaction_summary_message",
    "create_custom_message",
    "create_event_bus",
    "create_extension",
    "create_extension_runtime",
    "create_file_ops",
    "create_package_manager",
    "discover_and_load_extensions",
    "emit_session_shutdown_event",
    "estimate_context_tokens",
    "estimate_tokens",
    "exec_command",
    "execute_bash",
    "execute_bash_with_operations",
    "expand_prompt_template",
    "extract_file_ops_from_message",
    "find_cut_point",
    "find_initial_model",
    "find_most_recent_session",
    "find_turn_start_index",
    "format_file_operations",
    "format_skills_for_prompt",
    "generate_branch_summary",
    "generate_summary",
    "get_agent_dir",
    "get_last_assistant_usage",
    "get_latest_compaction_entry",
    "get_prompts_dir",
    "load_entries_from_file",
    "load_extension_from_factory",
    "load_extensions",
    "load_prompt_templates",
    "load_skills",
    "load_skills_from_dir",
    "migrate_session_entries",
    "parse_command_args",
    "parse_model_pattern",
    "parse_session_entries",
    "parse_skill_block",
    "prepare_branch_entries",
    "prepare_compaction",
    "print_timings",
    "resolve_cli_model",
    "resolve_config_value",
    "resolve_headers",
    "resolve_model_scope",
    "restore_model_from_session",
    "serialize_conversation",
    "should_compact",
    "substitute_args",
    "time",
    "wrap_registered_tool",
    "wrap_registered_tools",
    "wrap_tool_with_extensions",
    "wrap_tools_with_extensions",
]
