"""Data layer — PostgreSQL persistence."""

from rolemesh.db.pg import (
    ChatInfo,
    close_database,
    create_task,
    delete_task,
    get_all_chats,
    get_all_registered_groups,
    get_all_sessions,
    get_all_tasks,
    get_due_tasks,
    get_last_group_sync,
    get_messages_since,
    get_new_messages,
    get_registered_group,
    get_router_state,
    get_session,
    get_task_by_id,
    get_tasks_for_group,
    init_database,
    log_task_run,
    set_last_group_sync,
    set_registered_group,
    set_router_state,
    set_session,
    store_chat_metadata,
    store_message,
    store_message_direct,
    update_chat_name,
    update_task,
    update_task_after_run,
)

# Test helper — only import when needed
from rolemesh.db.pg import _init_test_database as _init_test_database

__all__ = [
    "ChatInfo",
    "_init_test_database",
    "close_database",
    "create_task",
    "delete_task",
    "get_all_chats",
    "get_all_registered_groups",
    "get_all_sessions",
    "get_all_tasks",
    "get_due_tasks",
    "get_last_group_sync",
    "get_messages_since",
    "get_new_messages",
    "get_registered_group",
    "get_router_state",
    "get_session",
    "get_task_by_id",
    "get_tasks_for_group",
    "init_database",
    "log_task_run",
    "set_last_group_sync",
    "set_registered_group",
    "set_router_state",
    "set_session",
    "store_chat_metadata",
    "store_message",
    "store_message_direct",
    "update_chat_name",
    "update_task",
    "update_task_after_run",
]
