"""Catch ``contracts/openapi.yaml`` <-> ``web/src/api/generated/types.ts`` drift.

The TS types are generated by ``openapi-typescript``. Once the yaml
is the source of truth, the generated file *must* be committed so
frontend devs don't have to run npm scripts on first checkout (per
the design decision to use OpenAPI as the contract spine).

This test runs the codegen against the live yaml in a tmp dir and
byte-diffs it against the committed copy. Anything that drifts —
a new endpoint added to the yaml but not regenerated, an enum
narrowed in the yaml, an operationId rename — flips this test red.

Anti-mirror: we deliberately don't re-parse the yaml or re-derive
the expected TS structure; we exercise the same codegen tool the
frontend uses, so a regression in the tool *or* the source ships
back to the developer fast.

Path note (PR22): the yaml now lives in the top-level ``contracts/``
folder so it's no longer implied-owned by the frontend tree. The
generated TS still lives under ``web/`` because it's a frontend build
artifact; the Pydantic models still live under ``src/webui/`` because
they're the backend's implementation of the same contract.
"""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
WEB = REPO_ROOT / "web"
YAML = REPO_ROOT / "contracts" / "openapi.yaml"
COMMITTED_TS = WEB / "src/api/generated/types.ts"
BIN = WEB / "node_modules/.bin/openapi-typescript"


def _have_codegen() -> bool:
    # The bin file is created by ``npm install`` in web/. If it's
    # missing we have to skip rather than fail — the user may be
    # running pytest without having bootstrapped the web tree.
    return BIN.is_file() and shutil.which("node") is not None


@pytest.mark.skipif(
    not _have_codegen(),
    reason="run `npm install` in web/ to enable openapi codegen freshness check",
)
def test_committed_types_are_up_to_date(tmp_path: Path) -> None:
    out = tmp_path / "types.ts"
    result = subprocess.run(
        [str(BIN), str(YAML), "-o", str(out)],
        cwd=str(WEB),
        capture_output=True,
        text=True,
        timeout=120,
    )
    assert result.returncode == 0, (
        "openapi-typescript exited non-zero:\n"
        f"stdout:\n{result.stdout}\nstderr:\n{result.stderr}"
    )
    assert out.is_file(), "codegen did not write the output file"

    generated = out.read_text(encoding="utf-8")
    committed = COMMITTED_TS.read_text(encoding="utf-8")

    if generated != committed:
        # Show a head-of-diff so the failure message is actionable.
        # Diff at the line level — full file is ~850 lines and an
        # entire dump would drown the actual problem.
        diff = subprocess.run(
            ["diff", "-u", str(COMMITTED_TS), str(out)],
            capture_output=True,
            text=True,
            timeout=10,
        )
        # diff returns 1 when files differ; that's expected here.
        pytest.fail(
            "web/src/api/generated/types.ts is stale vs contracts/openapi.yaml.\n"
            "Re-run `npm run openapi:gen` in web/ and commit the result.\n"
            "--- diff (first 80 lines) ---\n"
            + "\n".join(diff.stdout.splitlines()[:80])
        )


def test_codegen_output_carries_do_not_edit_marker() -> None:
    """The committed file must look generated.

    A common failure mode is somebody edits ``types.ts`` directly
    (without re-running codegen) and ships it. The codegen banner
    is the cheapest signal to catch that. This test runs whether
    or not node is installed locally so reviewers always see the
    expectation enforced.
    """
    head = COMMITTED_TS.read_text(encoding="utf-8")[:512]
    assert "auto-generated" in head.lower(), (
        "types.ts is missing the codegen banner — was it hand-edited?"
    )
