"""Agent runtime with tool calling — Python port of @mariozechner/pi-agent-core."""

from pi.agent.agent import Agent, AgentOptions
from pi.agent.agent_loop import agent_loop, agent_loop_continue
from pi.agent.proxy import stream_proxy
from pi.agent.types import (
    AgentContext,
    AgentEndEvent,
    AgentEvent,
    AgentLoopConfig,
    AgentMessage,
    AgentStartEvent,
    AgentState,
    AgentTool,
    AgentToolResult,
    AgentToolUpdateCallback,
    CustomAgentMessages,
    MessageEndEvent,
    MessageStartEvent,
    MessageUpdateEvent,
    PromptTurnCompleteEvent,
    ProxyAssistantMessageEvent,
    ProxyDoneEvent,
    ProxyErrorEvent,
    ProxyStartEvent,
    ProxyStreamOptions,
    ProxyTextDeltaEvent,
    ProxyTextEndEvent,
    ProxyTextStartEvent,
    ProxyThinkingDeltaEvent,
    ProxyThinkingEndEvent,
    ProxyThinkingStartEvent,
    ProxyToolCallDeltaEvent,
    ProxyToolCallEndEvent,
    ProxyToolCallStartEvent,
    StreamFn,
    ThinkingLevel,
    ToolExecutionEndEvent,
    ToolExecutionStartEvent,
    ToolExecutionUpdateEvent,
    TurnEndEvent,
    TurnStartEvent,
)

__all__ = [
    "Agent",
    "AgentContext",
    "AgentEndEvent",
    "AgentEvent",
    "AgentLoopConfig",
    "AgentMessage",
    "AgentOptions",
    "AgentStartEvent",
    "AgentState",
    "AgentTool",
    "AgentToolResult",
    "AgentToolUpdateCallback",
    "CustomAgentMessages",
    "MessageEndEvent",
    "MessageStartEvent",
    "MessageUpdateEvent",
    "PromptTurnCompleteEvent",
    "ProxyAssistantMessageEvent",
    "ProxyDoneEvent",
    "ProxyErrorEvent",
    "ProxyStartEvent",
    "ProxyStreamOptions",
    "ProxyTextDeltaEvent",
    "ProxyTextEndEvent",
    "ProxyTextStartEvent",
    "ProxyThinkingDeltaEvent",
    "ProxyThinkingEndEvent",
    "ProxyThinkingStartEvent",
    "ProxyToolCallDeltaEvent",
    "ProxyToolCallEndEvent",
    "ProxyToolCallStartEvent",
    "StreamFn",
    "ThinkingLevel",
    "ToolExecutionEndEvent",
    "ToolExecutionStartEvent",
    "ToolExecutionUpdateEvent",
    "TurnEndEvent",
    "TurnStartEvent",
    "agent_loop",
    "agent_loop_continue",
    "stream_proxy",
]
